script:
  - "bundle exec rake neo4j:install['community-2.2.0-M02'] neo4j:start default --trace"
language: ruby
cache: bundler

rvm:
  - 2.3.1

#notifications:
#  webhooks:
#    urls:
#      # send travis build-related statsd to an app (that forwards it to enova.graphite.com)
#      - http://travis.enova.com:4568/payload
email:
  recipients:
    - jshanthi19@gmail.com
    
before_install:
  - gem update --system
  - gem --version    
  
script:
  - RAILS_ENV=test bundle exec rake teaspoon
  - RAILS_ENV=test xvfb-run -a bundle exec rake parallel:spec  
  
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - export PARALLEL_TEST_PROCESSORS=4
  - RAILS_ENV=development bundle exec rake db:create db:migrate
  - bundle exec rake parallel:create parallel:load_schema parallel:prepare  
    

#env:
#  matrix:
#    - TEST_COMMAND="wud_tools/file_type_validator.sh"
#    - TEST_COMMAND="mdl main/ qa/ scripts/"

# script:
#  - bundle exec $TEST_COMMAND
