language: ruby
cache: bundler

rvm:
  - 2.3.1

#notifications:
#  webhooks:
#    urls:
#      # send travis build-related statsd to an app (that forwards it to enova.graphite.com)
#      - http://travis.enova.com:4568/payload
email:
  recipients:
    - jshanthi19@gmail.com

#env:
#  matrix:
#    - TEST_COMMAND="wud_tools/file_type_validator.sh"
#    - TEST_COMMAND="mdl main/ qa/ scripts/"

# script:
#  - bundle exec $TEST_COMMAND
